-- REVIEW CANDIDATE ONLY. DO NOT APPLY WITHOUT EXPLICIT PRODUCTION DDL APPROVAL.
-- Authorizes bounded server-side continuation of one paper AG cycle.
create table if not exists public.ag_cycle_worker_authorizations (
  id uuid primary key default gen_random_uuid(),
  cycle_id uuid not null unique references public.ag_daily_cycles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  token_hash text not null unique,
  status text not null default 'active' check (status in ('active','consumed','revoked','expired')),
  expires_at timestamptz not null,
  max_invocations integer not null default 32 check (max_invocations between 1 and 64),
  invocation_count integer not null default 0 check (invocation_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_invoked_at timestamptz,
  check (expires_at > created_at)
);

alter table public.ag_cycle_worker_authorizations enable row level security;
revoke all on table public.ag_cycle_worker_authorizations from public, anon, authenticated;
grant select, insert, update on table public.ag_cycle_worker_authorizations to service_role;

create index if not exists ag_cycle_worker_authorizations_active_idx
on public.ag_cycle_worker_authorizations(cycle_id,status,expires_at);

-- The signed-in user may mint one capability only for their own currently
-- running paper AG cycle. The raw token is generated by the application; only
-- its SHA-256 hex digest is stored.
create or replace function public.ag_authorize_cycle_worker(
  p_cycle_id uuid,
  p_token_hash text,
  p_ttl_minutes integer default 180,
  p_max_invocations integer default 32
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_auth_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_token_hash !~ '^[0-9a-f]{64}$' then raise exception 'Invalid worker token digest'; end if;
  if p_ttl_minutes < 5 or p_ttl_minutes > 360 then raise exception 'Invalid worker authorization TTL'; end if;
  if p_max_invocations < 1 or p_max_invocations > 64 then raise exception 'Invalid worker invocation limit'; end if;

  if not exists (
    select 1
    from public.ag_daily_cycles c
    join public.portfolios p on p.id=c.portfolio_id and p.user_id=c.user_id
    join public.portfolio_strategy_eras e on e.id=c.strategy_era_id and e.portfolio_id=c.portfolio_id and e.user_id=c.user_id
    where c.id=p_cycle_id and c.user_id=v_user_id and c.status='running'
      and p.type='paper_active' and p.is_real_money=false
      and e.strategy_key='accelerated_growth' and e.execution_mode='paper' and e.ended_at is null
  ) then raise exception 'Eligible running paper AG cycle required'; end if;

  insert into public.ag_cycle_worker_authorizations(
    cycle_id,user_id,token_hash,status,expires_at,max_invocations,invocation_count,updated_at
  ) values (
    p_cycle_id,v_user_id,p_token_hash,'active',now()+make_interval(mins=>p_ttl_minutes),p_max_invocations,0,now()
  )
  on conflict(cycle_id) do update
    set token_hash=excluded.token_hash,status='active',expires_at=excluded.expires_at,
        max_invocations=excluded.max_invocations,invocation_count=0,last_invoked_at=null,updated_at=now()
    where public.ag_cycle_worker_authorizations.user_id=v_user_id
      and public.ag_cycle_worker_authorizations.status in ('revoked','expired','consumed')
  returning id into v_auth_id;

  if v_auth_id is null then raise exception 'Active worker authorization already exists'; end if;
  return v_auth_id;
end;
$$;

revoke all on function public.ag_authorize_cycle_worker(uuid,text,integer,integer) from public, anon;
grant execute on function public.ag_authorize_cycle_worker(uuid,text,integer,integer) to authenticated;
grant execute on function public.ag_authorize_cycle_worker(uuid,text,integer,integer) to service_role;

-- Server-only atomic claim. service_role bypasses RLS but still must present the
-- exact cycle-bound token digest. FOR UPDATE serializes concurrent worker wakes.
create or replace function public.ag_claim_cycle_worker(
  p_cycle_id uuid,
  p_token_hash text
) returns table(authorization_id uuid,user_id uuid,invocation_number integer,max_candidates integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_auth public.ag_cycle_worker_authorizations%rowtype;
begin
  select * into v_auth
  from public.ag_cycle_worker_authorizations
  where cycle_id=p_cycle_id and token_hash=p_token_hash
  for update;

  if not found then return; end if;
  if v_auth.status <> 'active' then return; end if;

  if v_auth.expires_at <= now() then
    update public.ag_cycle_worker_authorizations
      set status='expired',updated_at=now() where id=v_auth.id;
    return;
  end if;

  if v_auth.invocation_count >= v_auth.max_invocations then
    update public.ag_cycle_worker_authorizations
      set status='revoked',updated_at=now() where id=v_auth.id;
    return;
  end if;

  if not exists (
    select 1 from public.ag_daily_cycles c
    join public.portfolios p on p.id=c.portfolio_id and p.user_id=c.user_id
    join public.portfolio_strategy_eras e on e.id=c.strategy_era_id and e.portfolio_id=c.portfolio_id and e.user_id=c.user_id
    where c.id=v_auth.cycle_id and c.user_id=v_auth.user_id and c.status='running'
      and p.type='paper_active' and p.is_real_money=false
      and e.strategy_key='accelerated_growth' and e.execution_mode='paper' and e.ended_at is null
  ) then
    update public.ag_cycle_worker_authorizations
      set status='revoked',updated_at=now() where id=v_auth.id;
    return;
  end if;

  update public.ag_cycle_worker_authorizations
    set invocation_count=invocation_count+1,last_invoked_at=now(),updated_at=now()
    where id=v_auth.id
    returning id,public.ag_cycle_worker_authorizations.user_id,invocation_count
    into authorization_id,user_id,invocation_number;
  select c.max_candidates into max_candidates from public.ag_daily_cycles c where c.id=v_auth.cycle_id and c.user_id=v_auth.user_id;
  return next;
end;
$$;

revoke all on function public.ag_claim_cycle_worker(uuid,text) from public, anon, authenticated;
grant execute on function public.ag_claim_cycle_worker(uuid,text) to service_role;

create or replace function public.ag_finish_cycle_worker(
  p_cycle_id uuid,
  p_token_hash text,
  p_terminal_status text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not (p_terminal_status = any(array['consumed','revoked'])) then raise exception 'Invalid terminal worker status'; end if;
  update public.ag_cycle_worker_authorizations
    set status=p_terminal_status,updated_at=now()
    where cycle_id=p_cycle_id and token_hash=p_token_hash and status='active';
  return found;
end;
$$;

revoke all on function public.ag_finish_cycle_worker(uuid,text,text) from public, anon, authenticated;
grant execute on function public.ag_finish_cycle_worker(uuid,text,text) to service_role;


-- Service-role-only delegation helper. Every worker operation supplies the
-- authorization id + cycle + token digest. The helper revalidates all three,
-- expiry, invocation budget and paper-only ownership before locally binding
-- auth.uid() for the existing hardened RPC. set_config(..., true) is
-- transaction-local and does not create or expose a user session/JWT.
create or replace function public.ag_bind_cycle_worker_identity(
  p_authorization_id uuid,p_cycle_id uuid,p_token_hash text
) returns uuid
language plpgsql security definer set search_path=''
as $$
declare v_auth public.ag_cycle_worker_authorizations%rowtype;
begin
 select * into v_auth from public.ag_cycle_worker_authorizations
 where id=p_authorization_id and cycle_id=p_cycle_id and token_hash=p_token_hash
   and status='active' and expires_at>now() and invocation_count<=max_invocations;
 if not found then raise exception 'Valid AG worker authorization required'; end if;
 if not exists (
  select 1 from public.ag_daily_cycles c
  join public.portfolios p on p.id=c.portfolio_id and p.user_id=c.user_id
  join public.portfolio_strategy_eras e on e.id=c.strategy_era_id and e.portfolio_id=c.portfolio_id and e.user_id=c.user_id
  where c.id=v_auth.cycle_id and c.user_id=v_auth.user_id and c.status='running'
    and p.type='paper_active' and p.is_real_money=false
    and e.strategy_key='accelerated_growth' and e.execution_mode='paper' and e.ended_at is null
 ) then raise exception 'Eligible running paper AG cycle required'; end if;
 perform set_config('request.jwt.claim.sub',v_auth.user_id::text,true);
 return v_auth.user_id;
end;
$$;
revoke all on function public.ag_bind_cycle_worker_identity(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.ag_bind_cycle_worker_identity(uuid,uuid,text) to service_role;

create or replace function public.ag_worker_read_cycle_checkpoint_status(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text
) returns table(checkpoint_id uuid,stage text,status text,attempt_count integer,started_at timestamptz,completed_at timestamptz,lease_expires_at timestamptz,updated_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 return query select * from public.ag_read_cycle_checkpoint_status(p_cycle_id);
end $$;

create or replace function public.ag_worker_read_completed_stage_output(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_stage text
) returns table(checkpoint_id uuid,stage text,output jsonb,completed_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 return query select * from public.ag_read_completed_stage_output(p_cycle_id,p_stage);
end $$;

create or replace function public.ag_worker_claim_cycle_stage(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_stage text
) returns table(checkpoint_id uuid,claim_token uuid)
language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 return query select * from public.ag_claim_cycle_stage(p_cycle_id,p_stage);
end $$;

create or replace function public.ag_worker_complete_cycle_stage(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_checkpoint_id uuid,p_claim_token uuid,p_output jsonb
) returns boolean language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 if not exists(select 1 from public.ag_cycle_stage_checkpoints where id=p_checkpoint_id and cycle_id=p_cycle_id) then return false; end if;
 return public.ag_complete_cycle_stage(p_checkpoint_id,p_claim_token,p_output);
end $$;

create or replace function public.ag_worker_read_cycle_symbol_checkpoints(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_parent_stage text
) returns table(symbol text,status text,output jsonb)
language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 return query select * from public.ag_read_cycle_symbol_checkpoints(p_cycle_id,p_parent_stage);
end $$;

create or replace function public.ag_worker_claim_cycle_symbol(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_parent_stage text,p_symbol text
) returns table(checkpoint_id uuid,claim_token uuid)
language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 return query select * from public.ag_claim_cycle_symbol(p_cycle_id,p_parent_stage,p_symbol);
end $$;

create or replace function public.ag_worker_complete_cycle_symbol(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_checkpoint_id uuid,p_claim_token uuid,p_output jsonb
) returns boolean language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 if not exists(select 1 from public.ag_cycle_symbol_checkpoints where id=p_checkpoint_id and cycle_id=p_cycle_id) then return false; end if;
 return public.ag_complete_cycle_symbol(p_checkpoint_id,p_claim_token,p_output);
end $$;

create or replace function public.ag_worker_reclaim_expired_symbol_parent_stage(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_stage text
) returns table(checkpoint_id uuid,claim_token uuid)
language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 return query select * from public.ag_reclaim_expired_symbol_parent_stage(p_cycle_id,p_stage);
end $$;

revoke all on function public.ag_worker_read_cycle_checkpoint_status(uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.ag_worker_read_completed_stage_output(uuid,uuid,text,text) from public,anon,authenticated;
revoke all on function public.ag_worker_claim_cycle_stage(uuid,uuid,text,text) from public,anon,authenticated;
revoke all on function public.ag_worker_complete_cycle_stage(uuid,uuid,text,uuid,uuid,jsonb) from public,anon,authenticated;
revoke all on function public.ag_worker_read_cycle_symbol_checkpoints(uuid,uuid,text,text) from public,anon,authenticated;
revoke all on function public.ag_worker_claim_cycle_symbol(uuid,uuid,text,text,text) from public,anon,authenticated;
revoke all on function public.ag_worker_complete_cycle_symbol(uuid,uuid,text,uuid,uuid,jsonb) from public,anon,authenticated;
revoke all on function public.ag_worker_reclaim_expired_symbol_parent_stage(uuid,uuid,text,text) from public,anon,authenticated;
grant execute on function public.ag_worker_read_cycle_checkpoint_status(uuid,uuid,text) to service_role;
grant execute on function public.ag_worker_read_completed_stage_output(uuid,uuid,text,text) to service_role;
grant execute on function public.ag_worker_claim_cycle_stage(uuid,uuid,text,text) to service_role;
grant execute on function public.ag_worker_complete_cycle_stage(uuid,uuid,text,uuid,uuid,jsonb) to service_role;
grant execute on function public.ag_worker_read_cycle_symbol_checkpoints(uuid,uuid,text,text) to service_role;
grant execute on function public.ag_worker_claim_cycle_symbol(uuid,uuid,text,text,text) to service_role;
grant execute on function public.ag_worker_complete_cycle_symbol(uuid,uuid,text,uuid,uuid,jsonb) to service_role;
grant execute on function public.ag_worker_reclaim_expired_symbol_parent_stage(uuid,uuid,text,text) to service_role;


-- Durability wrappers reuse the same cycle capability and existing hardened
-- persistence/finalization RPCs. They remain service-role-only and paper-only.
create or replace function public.ag_worker_commit_cycle_decision(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_claim_token uuid,p_ticker text,p_kind text,p_decision_type text,p_thesis text,p_confidence numeric,p_thesis_clock text,p_bull_case text,p_bear_case text,p_monitoring text,p_invalidation text,p_notes text,p_ag_thesis_valid boolean,p_ag_liquidity_eligible boolean,p_ag_evidence_version text,p_ag_theme_key text
) returns uuid language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 return public.ag_commit_cycle_decision(p_cycle_id,p_claim_token,p_ticker,p_kind,p_decision_type,p_thesis,p_confidence,p_thesis_clock,p_bull_case,p_bear_case,p_monitoring,p_invalidation,p_notes,p_ag_thesis_valid,p_ag_liquidity_eligible,p_ag_evidence_version,p_ag_theme_key);
end $$;

create or replace function public.ag_worker_commit_watch_operation(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_claim_token uuid,p_stream text,p_ticker text,p_action text,p_source_row_id uuid,p_resolution text,p_company_name text,p_confidence numeric,p_thesis text,p_unresolved_questions text[],p_thesis_clock text,p_invalidation text[],p_model text,p_prompt_version text,p_prior_watch_reassessed boolean
) returns uuid language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 return public.ag_commit_watch_operation(p_cycle_id,p_claim_token,p_stream,p_ticker,p_action,p_source_row_id,p_resolution,p_company_name,p_confidence,p_thesis,p_unresolved_questions,p_thesis_clock,p_invalidation,p_model,p_prompt_version,p_prior_watch_reassessed);
end $$;

create or replace function public.ag_worker_verify_decision_manifest(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_kind text
) returns boolean language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 if p_kind='holding_review' then return public.ag_verify_holding_payload_manifest(p_cycle_id); end if;
 if p_kind='committee' then return public.ag_verify_committee_payload_manifest(p_cycle_id); end if;
 raise exception 'Invalid AG decision manifest kind';
end $$;

create or replace function public.ag_worker_verify_cycle_watch_manifest(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text
) returns boolean language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 return public.ag_verify_cycle_watch_manifest(p_cycle_id);
end $$;

create or replace function public.ag_worker_complete_persistence_stage(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_checkpoint_id uuid,p_claim_token uuid,p_expected_tickers text[]
) returns boolean language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 if not exists(select 1 from public.ag_cycle_stage_checkpoints where id=p_checkpoint_id and cycle_id=p_cycle_id and stage='persistence') then return false; end if;
 return public.ag_complete_persistence_stage(p_checkpoint_id,p_claim_token,p_expected_tickers);
end $$;

create or replace function public.ag_worker_finalize_daily_cycle(
 p_authorization_id uuid,p_cycle_id uuid,p_token_hash text,p_checkpoint_id uuid,p_claim_token uuid
) returns boolean language plpgsql security definer set search_path='' as $$
begin
 perform public.ag_bind_cycle_worker_identity(p_authorization_id,p_cycle_id,p_token_hash);
 if not exists(select 1 from public.ag_cycle_stage_checkpoints where id=p_checkpoint_id and cycle_id=p_cycle_id and stage='finalized') then return false; end if;
 return public.ag_finalize_daily_cycle(p_checkpoint_id,p_claim_token);
end $$;

revoke all on function public.ag_worker_commit_cycle_decision(uuid,uuid,text,uuid,text,text,text,text,numeric,text,text,text,text,text,text,boolean,boolean,text,text) from public,anon,authenticated;
revoke all on function public.ag_worker_commit_watch_operation(uuid,uuid,text,uuid,text,text,text,uuid,text,text,numeric,text,text[],text,text[],text,text,boolean) from public,anon,authenticated;
revoke all on function public.ag_worker_verify_decision_manifest(uuid,uuid,text,text) from public,anon,authenticated;
revoke all on function public.ag_worker_verify_cycle_watch_manifest(uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.ag_worker_complete_persistence_stage(uuid,uuid,text,uuid,uuid,text[]) from public,anon,authenticated;
revoke all on function public.ag_worker_finalize_daily_cycle(uuid,uuid,text,uuid,uuid) from public,anon,authenticated;
grant execute on function public.ag_worker_commit_cycle_decision(uuid,uuid,text,uuid,text,text,text,text,numeric,text,text,text,text,text,text,boolean,boolean,text,text) to service_role;
grant execute on function public.ag_worker_commit_watch_operation(uuid,uuid,text,uuid,text,text,text,uuid,text,text,numeric,text,text[],text,text[],text,text,boolean) to service_role;
grant execute on function public.ag_worker_verify_decision_manifest(uuid,uuid,text,text) to service_role;
grant execute on function public.ag_worker_verify_cycle_watch_manifest(uuid,uuid,text) to service_role;
grant execute on function public.ag_worker_complete_persistence_stage(uuid,uuid,text,uuid,uuid,text[]) to service_role;
grant execute on function public.ag_worker_finalize_daily_cycle(uuid,uuid,text,uuid,uuid) to service_role;
