-- REVIEW CANDIDATE ONLY. DO NOT APPLY WITHOUT EXPLICIT PRODUCTION DDL APPROVAL.
-- Authorizes bounded server-side continuation of one paper AG cycle.
create table if not exists public.ag_cycle_worker_authorizations (
  id uuid primary key default gen_random_uuid(),
  cycle_id uuid not null unique references public.ag_daily_cycles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  token_hash text not null unique,
  status text not null default 'active' check (status in ('active','consumed','revoked','expired')),
  expires_at timestamptz not null,
  max_invocations integer not null default 32 check (max_invocations between 1 and 64),
  invocation_count integer not null default 0 check (invocation_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_invoked_at timestamptz,
  check (expires_at > created_at)
);

alter table public.ag_cycle_worker_authorizations enable row level security;
revoke all on table public.ag_cycle_worker_authorizations from public, anon, authenticated;
grant select, insert, update on table public.ag_cycle_worker_authorizations to service_role;

create index if not exists ag_cycle_worker_authorizations_active_idx
on public.ag_cycle_worker_authorizations(cycle_id,status,expires_at);

-- The signed-in user may mint one capability only for their own currently
-- running paper AG cycle. The raw token is generated by the application; only
-- its SHA-256 hex digest is stored.
create or replace function public.ag_authorize_cycle_worker(
  p_cycle_id uuid,
  p_token_hash text,
  p_ttl_minutes integer default 180,
  p_max_invocations integer default 32
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_auth_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_token_hash !~ '^[0-9a-f]{64}$' then raise exception 'Invalid worker token digest'; end if;
  if p_ttl_minutes < 5 or p_ttl_minutes > 360 then raise exception 'Invalid worker authorization TTL'; end if;
  if p_max_invocations < 1 or p_max_invocations > 64 then raise exception 'Invalid worker invocation limit'; end if;

  if not exists (
    select 1
    from public.ag_daily_cycles c
    join public.portfolios p on p.id=c.portfolio_id and p.user_id=c.user_id
    join public.portfolio_strategy_eras e on e.id=c.strategy_era_id and e.portfolio_id=c.portfolio_id
    where c.id=p_cycle_id and c.user_id=v_user_id and c.status='running'
      and p.type='paper_active' and p.is_real_money=false
      and e.strategy_key='accelerated_growth' and e.execution_mode='paper' and e.ended_at is null
  ) then raise exception 'Eligible running paper AG cycle required'; end if;

  insert into public.ag_cycle_worker_authorizations(
    cycle_id,user_id,token_hash,status,expires_at,max_invocations,invocation_count,updated_at
  ) values (
    p_cycle_id,v_user_id,p_token_hash,'active',now()+make_interval(mins=>p_ttl_minutes),p_max_invocations,0,now()
  )
  on conflict(cycle_id) do update
    set token_hash=excluded.token_hash,status='active',expires_at=excluded.expires_at,
        max_invocations=excluded.max_invocations,invocation_count=0,last_invoked_at=null,updated_at=now()
    where public.ag_cycle_worker_authorizations.user_id=v_user_id
      and public.ag_cycle_worker_authorizations.status in ('revoked','expired','consumed')
  returning id into v_auth_id;

  if v_auth_id is null then raise exception 'Active worker authorization already exists'; end if;
  return v_auth_id;
end;
$$;

revoke all on function public.ag_authorize_cycle_worker(uuid,text,integer,integer) from public, anon;
grant execute on function public.ag_authorize_cycle_worker(uuid,text,integer,integer) to authenticated;
grant execute on function public.ag_authorize_cycle_worker(uuid,text,integer,integer) to service_role;

-- Server-only atomic claim. service_role bypasses RLS but still must present the
-- exact cycle-bound token digest. FOR UPDATE serializes concurrent worker wakes.
create or replace function public.ag_claim_cycle_worker(
  p_cycle_id uuid,
  p_token_hash text
) returns table(authorization_id uuid,user_id uuid,invocation_number integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_auth public.ag_cycle_worker_authorizations%rowtype;
begin
  select * into v_auth
  from public.ag_cycle_worker_authorizations
  where cycle_id=p_cycle_id and token_hash=p_token_hash
  for update;

  if not found then return; end if;
  if v_auth.status <> 'active' then return; end if;

  if v_auth.expires_at <= now() then
    update public.ag_cycle_worker_authorizations
      set status='expired',updated_at=now() where id=v_auth.id;
    return;
  end if;

  if v_auth.invocation_count >= v_auth.max_invocations then
    update public.ag_cycle_worker_authorizations
      set status='revoked',updated_at=now() where id=v_auth.id;
    return;
  end if;

  if not exists (
    select 1 from public.ag_daily_cycles c
    join public.portfolios p on p.id=c.portfolio_id and p.user_id=c.user_id
    join public.portfolio_strategy_eras e on e.id=c.strategy_era_id and e.portfolio_id=c.portfolio_id
    where c.id=v_auth.cycle_id and c.user_id=v_auth.user_id and c.status='running'
      and p.type='paper_active' and p.is_real_money=false
      and e.strategy_key='accelerated_growth' and e.execution_mode='paper' and e.ended_at is null
  ) then
    update public.ag_cycle_worker_authorizations
      set status='revoked',updated_at=now() where id=v_auth.id;
    return;
  end if;

  update public.ag_cycle_worker_authorizations
    set invocation_count=invocation_count+1,last_invoked_at=now(),updated_at=now()
    where id=v_auth.id
    returning id,public.ag_cycle_worker_authorizations.user_id,invocation_count
    into authorization_id,user_id,invocation_number;
  return next;
end;
$$;

revoke all on function public.ag_claim_cycle_worker(uuid,text) from public, anon, authenticated;
grant execute on function public.ag_claim_cycle_worker(uuid,text) to service_role;

create or replace function public.ag_finish_cycle_worker(
  p_cycle_id uuid,
  p_token_hash text,
  p_terminal_status text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_terminal_status not in ('consumed','revoked') then raise exception 'Invalid terminal worker status'; end if;
  update public.ag_cycle_worker_authorizations
    set status=p_terminal_status,updated_at=now()
    where cycle_id=p_cycle_id and token_hash=p_token_hash and status='active';
  return found;
end;
$$;

revoke all on function public.ag_finish_cycle_worker(uuid,text,text) from public, anon, authenticated;
grant execute on function public.ag_finish_cycle_worker(uuid,text,text) to service_role;
