import fs from "node:fs";
import assert from "node:assert/strict";
const root="lib/discovery/accelerated-growth/";
const transport=fs.readFileSync(root+"stage-checkpoint-supabase.ts","utf8");
const capture=fs.readFileSync(root+"stage-checkpoint-capture.ts","utf8");
const builders=fs.readFileSync(root+"stage-payload-builders.ts","utf8");
const executor=fs.readFileSync(root+"resumable-stage-executor.ts","utf8");
const stageWork=fs.readFileSync(root+"resumable-stage-work.ts","utf8");
const statusReader=fs.readFileSync(root+"stage-checkpoint-status-reader.ts","utf8");
const outputReader=fs.readFileSync(root+"stage-output-reader.ts","utf8");
const discoveryWork=fs.readFileSync(root+"discovery-stage-work.ts","utf8");
const deepWork=fs.readFileSync(root+"catalyst-deep-stage-work.ts","utf8");
const committeeWork=fs.readFileSync(root+"committee-stage-work.ts","utf8");
const researchStages=fs.readFileSync(root+"resumable-research-stages.ts","utf8");
const persistencePlan=fs.readFileSync(root+"persistence-stage-plan.ts","utf8");
const runner=fs.readFileSync(root+"daily-cycle-work.ts","utf8");
for(const [name,text] of [["transport",transport],["capture",capture],["builders",builders],["executor",executor],["stageWork",stageWork],["statusReader",statusReader],["outputReader",outputReader],["discoveryWork",discoveryWork],["deepWork",deepWork],["committeeWork",committeeWork],["researchStages",researchStages],["persistencePlan",persistencePlan]]){
 assert.ok(!text.includes("ag_commit_cycle_decision"),name+" must not persist decisions");
 assert.ok(!text.includes("ag_commit_watch_operation"),name+" must not persist watchlist");
 assert.ok(!text.includes("executeAgDailyCycleTransactions"),name+" must not execute transactions");
 assert.ok(!text.includes("daily-cycle-work"),name+" must not import active runner");
}
assert.ok(transport.includes('supabase.rpc("ag_claim_cycle_stage"'));
assert.ok(transport.includes('supabase.rpc("ag_complete_cycle_stage"'));
assert.ok(transport.includes("p_output:output.payload"));
assert.ok(transport.includes("supabase.auth.getUser()"));
assert.ok(executor.indexOf("rpc.claim") < executor.indexOf("input.run"));
assert.ok(executor.indexOf("input.run") < executor.indexOf("rpc.complete"));
assert.ok(!transport.includes('.from("ag_cycle_stage_checkpoints")'));
assert.ok(!runner.includes("stage-checkpoint-supabase"));
assert.ok(!runner.includes("stage-checkpoint-capture"));
assert.ok(!runner.includes("resumable-stage-executor"));
assert.ok(!runner.includes("stage-payload-builders"));
assert.ok(!runner.includes("resumable-stage-work"));
assert.ok(stageWork.includes("runAgHoldingReviewPipeline"));
assert.ok(stageWork.includes('stage:"holding_review"'));
assert.ok(statusReader.includes('supabase.rpc("ag_read_cycle_checkpoint_status"'));
assert.ok(!statusReader.includes('.from("ag_cycle_stage_checkpoints")'));
assert.ok(!runner.includes("stage-checkpoint-status-reader"));
assert.ok(!runner.includes("resume-planner"));
assert.ok(outputReader.includes('supabase.rpc("ag_read_completed_stage_output"'));
assert.ok(!outputReader.includes('.from("ag_cycle_stage_checkpoints")'));
assert.ok(outputReader.includes("validateAgStageEnvelope"));
assert.ok(!runner.includes("stage-output-reader"));
for(const isolated of ["discovery-stage-work","catalyst-deep-stage-work","committee-stage-work","research-stage-payloads"]) assert.ok(!runner.includes(isolated));
assert.ok(discoveryWork.includes("runAcceleratedGrowthDiscovery"));
assert.ok(deepWork.includes("researchAgCatalyst")&&deepWork.includes("researchAgDeepCandidate"));
assert.ok(!deepWork.includes("runAcceleratedGrowthDiscovery"));
assert.ok(committeeWork.includes("runAgCommittee"));
assert.ok(!committeeWork.includes("runAgDeepResearchPipeline"));
assert.ok(!runner.includes("resumable-research-stages"));
assert.ok(!runner.includes("persistence-stage-plan"));
assert.ok(persistencePlan.includes("p_claim_token:claimToken"));
assert.ok(!persistencePlan.includes("supabase"));
assert.ok(!persistencePlan.includes("commitPreparedAgBatch"));
assert.ok(researchStages.includes('stage:"discovery"')&&researchStages.includes('stage:"catalyst_deep_research"')&&researchStages.includes('stage:"committee"'));
assert.ok(researchStages.includes("readAuthenticatedAgCompletedStageOutput"));
assert.ok(researchStages.includes("deriveAgExecutionEvidence(frozen)"));
assert.ok(researchStages.includes("parseAgDiscoveryStagePayload"));
assert.ok(researchStages.includes("parseAgDeepResearchResults"));
assert.ok(!researchStages.includes("getDynamicDiscoveryUniverse"));
assert.ok(runner.includes("assertAgLegacyPersistenceDisabled();"));
console.log("AG stage-capture isolation contract passed");
